#!/bin/bash
# ============================================================
#  Qwenta — VPS Setup Script (Ubuntu 20.04/22.04/24.04)
#  Run as: bash setup.sh
# ============================================================
set -e

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

log()  { echo -e "${CYAN}[Qwenta]${NC} $1"; }
ok()   { echo -e "${GREEN}[  OK  ]${NC} $1"; }
warn() { echo -e "${YELLOW}[ WARN ]${NC} $1"; }
err()  { echo -e "${RED}[ FAIL ]${NC} $1"; exit 1; }

echo ""
echo -e "${BOLD}${CYAN}"
echo "  ███╗   ██╗███████╗██╗  ██╗████████╗██████╗  █████╗ ██████╗ ███████╗"
echo "  ████╗  ██║██╔════╝╚██╗██╔╝╚══██╔══╝██╔══██╗██╔══██╗██╔══██╗██╔════╝"
echo "  ██╔██╗ ██║█████╗   ╚███╔╝    ██║   ██████╔╝███████║██║  ██║█████╗  "
echo "  ██║╚██╗██║██╔══╝   ██╔██╗    ██║   ██╔══██╗██╔══██║██║  ██║██╔══╝  "
echo "  ██║ ╚████║███████╗██╔╝ ██╗   ██║   ██║  ██║██║  ██║██████╔╝███████╗"
echo "  ╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ ╚══════╝"
echo -e "${NC}"
echo -e "  ${BOLD}Enterprise AI Trading Platform — VPS Setup${NC}"
echo ""

# ── 1. Check OS ──────────────────────────────────────────────
log "Checking system..."
if [ ! -f /etc/os-release ]; then err "Cannot detect OS"; fi
. /etc/os-release
if [[ "$ID" != "ubuntu" && "$ID" != "debian" ]]; then
  warn "This script is tested on Ubuntu/Debian. Proceeding anyway..."
fi
ok "OS: $PRETTY_NAME"

# ── 2. Check Node.js ────────────────────────────────────────
log "Checking Node.js..."
if ! command -v node &>/dev/null; then
  log "Installing Node.js 20 via NodeSource..."
  curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
  sudo apt-get install -y nodejs
fi
NODE_VER=$(node --version)
ok "Node.js: $NODE_VER"

# ── 3. Install PostgreSQL ────────────────────────────────────
log "Checking PostgreSQL..."
if ! command -v psql &>/dev/null; then
  log "Installing PostgreSQL..."
  sudo apt-get update -qq
  sudo apt-get install -y postgresql postgresql-contrib
  sudo systemctl start postgresql
  sudo systemctl enable postgresql
  ok "PostgreSQL installed and started"
else
  ok "PostgreSQL already installed"
  sudo systemctl start postgresql 2>/dev/null || true
fi

# ── 4. Create DB and user ────────────────────────────────────
log "Setting up database..."
DB_USER="qwenta"
DB_PASS=$(openssl rand -hex 16)
DB_NAME="qwenta"

# Create user and DB (idempotent)
sudo -u postgres psql -tc "SELECT 1 FROM pg_user WHERE usename='$DB_USER'" | grep -q 1 || \
  sudo -u postgres psql -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASS';"
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" | grep -q 1 || \
  sudo -u postgres psql -c "CREATE DATABASE $DB_NAME OWNER $DB_USER;"
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;"

DATABASE_URL="postgresql://$DB_USER:$DB_PASS@localhost:5432/$DB_NAME"
ok "Database ready: $DB_NAME (user: $DB_USER)"

# ── 5. Check Ollama ──────────────────────────────────────────
log "Checking Ollama..."
if ! command -v ollama &>/dev/null; then
  log "Installing Ollama..."
  curl -fsSL https://ollama.com/install.sh | sh
  ok "Ollama installed"
else
  ok "Ollama already installed"
fi

# Start Ollama service if not running
if ! systemctl is-active --quiet ollama 2>/dev/null; then
  log "Starting Ollama service..."
  sudo systemctl start ollama 2>/dev/null || ollama serve &>/dev/null &
  sleep 3
fi

# Pull Qwen model
log "Pulling qwen2.5 model (this may take a few minutes)..."
ollama pull qwen2.5 && ok "qwen2.5 ready" || warn "Could not pull qwen2.5, run manually: ollama pull qwen2.5"

# ── 6. Generate session secret ───────────────────────────────
SESSION_SECRET=$(openssl rand -hex 32)

# ── 7. Write .env ────────────────────────────────────────────
log "Writing .env file..."
cat > .env <<EOF
# Qwenta Environment Configuration
# Generated by setup.sh on $(date)

# Database
DATABASE_URL=$DATABASE_URL

# Ollama AI
OLLAMA_BASE_URL=http://localhost:11434
OLLAMA_MODEL=qwen2.5

# Session (DO NOT SHARE)
SESSION_SECRET=$SESSION_SECRET

# App
PUBLIC_APP_URL=http://localhost:4321
PUBLIC_APP_NAME=Qwenta
EOF
ok ".env written"

# ── 8. Install dependencies ──────────────────────────────────
log "Installing npm dependencies..."
npm install --silent && ok "npm install done"

# ── 9. Run migrations ────────────────────────────────────────
log "Running database migrations..."
node scripts/migrate.js && ok "Database schema ready"

# ── 10. Build ────────────────────────────────────────────────
log "Building Qwenta for production..."
npm run build && ok "Build complete → dist/"

# ── 11. Setup systemd service ────────────────────────────────
log "Setting up systemd service..."
APP_DIR=$(pwd)
APP_USER=$(whoami)

sudo tee /etc/systemd/system/qwenta.service > /dev/null <<EOF
[Unit]
Description=Qwenta Enterprise Trading Platform
After=network.target postgresql.service
Requires=postgresql.service

[Service]
Type=simple
User=$APP_USER
WorkingDirectory=$APP_DIR
EnvironmentFile=$APP_DIR/.env
ExecStart=/usr/bin/node dist/server/entry.mjs
Restart=on-failure
RestartSec=5
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=qwenta

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable qwenta
sudo systemctl start qwenta
sleep 2

if systemctl is-active --quiet qwenta; then
  ok "Qwenta service running"
else
  warn "Service may have failed. Check: sudo journalctl -u qwenta -n 50"
fi

# ── 12. Install & configure Nginx (optional) ─────────────────
echo ""
read -rp "$(echo -e "${CYAN}[Qwenta]${NC} Install Nginx as reverse proxy? [y/N] ")" INSTALL_NGINX
if [[ "$INSTALL_NGINX" =~ ^[Yy]$ ]]; then
  read -rp "$(echo -e "${CYAN}[Qwenta]${NC} Enter your domain (e.g. qwenta.example.com): ")" DOMAIN

  sudo apt-get install -y nginx

  sudo tee /etc/nginx/sites-available/qwenta > /dev/null <<EOF
server {
    listen 80;
    server_name $DOMAIN;

    location / {
        proxy_pass http://127.0.0.1:4321;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;

        # SSE support for AI streaming
        proxy_buffering off;
        proxy_cache off;
    }
}
EOF

  sudo ln -sf /etc/nginx/sites-available/qwenta /etc/nginx/sites-enabled/
  sudo nginx -t && sudo systemctl reload nginx
  ok "Nginx configured for $DOMAIN"

  # Offer SSL
  read -rp "$(echo -e "${CYAN}[Qwenta]${NC} Setup SSL with Let's Encrypt (certbot)? [y/N] ")" INSTALL_SSL
  if [[ "$INSTALL_SSL" =~ ^[Yy]$ ]]; then
    sudo apt-get install -y certbot python3-certbot-nginx
    sudo certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos -m "admin@$DOMAIN" || \
      warn "Certbot failed. Make sure DNS for $DOMAIN points to this server."
    ok "SSL certificate installed"

    # Update .env with HTTPS URL
    sed -i "s|PUBLIC_APP_URL=.*|PUBLIC_APP_URL=https://$DOMAIN|" .env
    sudo systemctl restart qwenta
  fi
fi

# ── Done ─────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}══════════════════════════════════════════${NC}"
echo -e "${BOLD}${GREEN}  ✓ Qwenta setup complete!${NC}"
echo -e "${BOLD}${GREEN}══════════════════════════════════════════${NC}"
echo ""
echo -e "  ${CYAN}URL:${NC}       http://$(curl -s ifconfig.me 2>/dev/null || echo 'YOUR_IP'):4321"
echo -e "  ${CYAN}DB:${NC}        $DB_NAME @ localhost"
echo -e "  ${CYAN}DB User:${NC}   $DB_USER"
echo -e "  ${CYAN}DB Pass:${NC}   $DB_PASS"
echo ""
echo -e "  ${YELLOW}⚠  Save your DB credentials above!${NC}"
echo -e "  ${YELLOW}   .env file is at: $(pwd)/.env${NC}"
echo ""
echo -e "  ${BOLD}Useful commands:${NC}"
echo -e "  sudo systemctl status qwenta     # check app status"
echo -e "  sudo journalctl -u qwenta -f     # live logs"
echo -e "  sudo systemctl restart qwenta    # restart app"
echo -e "  npm run build && sudo systemctl restart qwenta  # redeploy"
echo ""
